name: ci-env  # This matches the environment name used in the workflow

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.13.7
  - numpy
  - pandas
  - flake8
  - pytest
  - pytest-cov
  - pip
  - pip:
    - -e .
